### ISSUE TITLE
DIDs with network name not supported?

### ISSUE THREAD

**Issue by nklomp** [ltonetwork/indexer#117]
Is there (planned) support for having the network name in the DID?

In order to distinguish between different networks (custom/private, mainnet, testnet), a DID often supports to include the network name in the DID itself, so that a resolver/registrar can determine what network/node to use for resolution/registration.

Example for LTO would be : 

`did:lto:testnet:3N6mZMgGqYn9EVAR2Vbf637iej4fFipECq8`

So the method specific id becomes testnet:3N6mZMgGqYn9EVAR2Vbf637iej4fFipECq8

The benefit is also that a DID cannot be copied to another network and thus a potential attack vector if addresses do not use a different derivation path between them.

Basically every network except for mainnet would get the network in there. mainnet would leave out the network altogether.

Currently a call results in the below error:
```shell
curl -X 'GET' \
  'http://localhost/identities/did%3Alto%3Atestnet%3A3N6mZMgGqYn9EVAR2Vbf637iej4fFipECq8' \
  -H 'accept: */*'
```

Response:
```json
{
  "error": "failed to get DID document 'TypeError: Cannot read property 'groups' of null'"
}
```

Which is caused by the REGEX obviously not supporting it in the indexer at https://github.com/ltonetwork/indexer/blob/master/src/identity/identity.service.ts#L21 :
```javascript
const {address} = did.match(/^(?:did:lto:)?(?<address>\w+)(?::derived:(?<secret>\w+))?$/).groups;
```

The following part of the DID-Core spec is relevant here as well: https://www.w3.org/TR/did-core/#method-syntax
especially bullet points 4 to 8 and the note:

> 4. **_The method-specific-id value MUST be unique within a DID method_**. The method-specific-id value itself might be globally unique.
> 5. **_Any DID generated by a DID method MUST be globally unique._**
> 6. To reduce the chances of method-name conflicts, a DID method specification SHOULD be registered in the DID Specification Registries [DID-SPEC-REGISTRIES].
> 7. A DID method MAY define multiple method-specific-id formats.
> 8. The method-specific-id format MAY include colons. The use of colons MUST comply syntactically with the method-specific-id ABNF rule.

**Comment by jasny** [comment]
The second bytes of the address is the network id (`L` for mainnet and `T` for testnet). So every network address is globally unique. It's possible to determine and choose the correct network by base58 decoding the address part of the DID.

`3Jq3F3njrrR1ZvM3JhwLX2Sh56LQDtuEyu9` is a mainnet address
* https://nodes.lto.network/addresses/validate/3Jq3F3njrrR1ZvM3JhwLX2Sh56LQDtuEyu9
* https://testnet.lto.network/addresses/validate/3Jq3F3njrrR1ZvM3JhwLX2Sh56LQDtuEyu9

`3N6mZMgGqYn9EVAR2Vbf637iej4fFipECq8` is a testnet address
* https://nodes.lto.network/addresses/validate/3N6mZMgGqYn9EVAR2Vbf637iej4fFipECq8
* https://testnet.lto.network/addresses/validate/3N6mZMgGqYn9EVAR2Vbf637iej4fFipECq8

**Comment by nklomp** [comment]
Then please describe that in the DID documentation
