### ISSUE TITLE
Add "Supply" endpoints

### ISSUE THREAD

**Issue by justmvg** [ltonetwork/indexer#98]
As CMC requires an API to fetch supply data for blockchains, a new endpoint should be created

- circulating supply (take unlock excel file, burn address(es) and on-chain burn into account)
- max supply

CMC requires the output of the API to be the raw number including 8 decimals.

example HTTP response:
```
HTTP/1.1 200 OK
Date: Tue, 06 Jul 2021 14:29:29 GMT
Content-Type: text/plain

77908483.88736623
```

a raw `77908483.88736623` should be returned.

Perhaps make a default with JSON and make it raw if ?output=raw is applied as URL parameter.
example: `http://chainz.cryptoid.info/grs/api.dws?q=totalcoins`

**Comment by jasny** [comment]
The burn address is [3JrGV6TeEV3ovVjsh9SPqQL48EDLET47B9U](https://explorer.lto.network/address/3JrGV6TeEV3ovVjsh9SPqQL48EDLET47B9U)
